### ISSUE TITLE
design contribution

### ISSUE THREAD

**Issue by masudr4n4** [amalrajan/MorseCode-Translator#1]
hallo
nice to meet this projects.want to make a logo for this projects if you have any requirements then let me know.its free for any open source projects.

**Comment by amalrajan** [comment]
@maaudrana Thanks for showing your interest in the project. You're definitely welcome to submit a PR once you create the logo :)

**Comment by masudr4n4** [comment]
I have created three logos for you, which one of your choice tells me that I'll give you that source file. If you think something needs to be changed then you can tell me I'll change.

![morsecode translator-01](https://user-images.githubusercontent.com/34313493/40611288-83fd8402-6297-11e8-96f4-ff973772f949.jpg)

**Comment by amalrajan** [comment]
@maaudrana I think the third one looks quite meaningful and adheres well to the flat design concept. Please create a pull request for this one :)

**Comment by masudr4n4** [comment]
Thank you sir plzz check #2

**Comment by masudr4n4** [comment]
All the source file of the logo 
<a href="https://drive.google.com/drive/folders/1UUPns1Mte0mPF0Rc5NYpFX4LCrJYWFkV?usp=sharing">Here</a> you can use that as your wish.
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
